### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by ursvasan** [lusis/chef-kibana#117] opened 2016-02-23 02:32 UTC
I am trying to install kibana using this cookbook. in my cookbook i created a provider kibana.rb and i am calling the cookbook (similar to the kibana_lwrp::install recipe)

providers/kibana.rb
```
kibana_install 'kibana' do
  user kibana_user
  group kibana_user
  install_dir node['kibana']['install_dir']
  install_type install_type
  action :create
end
```

when i run ' kitchen test ' i get the following error
```
 ================================================================================
             Error executing action `create` on resource 'kibana_install[kibana]'
             ================================================================================
             
             NoMethodError
             -------------
             undefined method `[]' for nil:NilClass
             
             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/kibana_lwrp/libraries/install.rb:21:in `block in <class:KibanaInstall>'
             /tmp/kitchen/cache/cookbooks/kibana_lwrp/libraries/install.rb:116:in `kibana_resources'
             /tmp/kitchen/cache/cookbooks/kibana_lwrp/libraries/install.rb:46:in `block in <class:KibanaInstall>'
             
       
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/mycookbook/providers/kibana.rb
             
       34: kibana_install 'kibana' do
       35:   user kibana_user
       36:   group kibana_user
       37:   install_dir node['kibana']['install_dir']
       38:   install_type install_type
       39:   action :create
       40: end
       41: 
             
             Compiled Resource:
             ------------------
       # Declared in /tmp/kitchen/cache/cookbooks/mycookbook/providers/kibana.rb:34:in `block in class_from_file'
             
             kibana_install("kibana") do
        action [:create]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :kibana_install
        cookbook_name "mycookbook"
        user "kibana"
        group "kibana"
        install_dir "/opt/kibana"
        install_type "file"
             end
             
           
           ================================================================================
           Error executing action `deploy` on resource 'mycookbook_kibana[install_kibana]'
           ================================================================================
           
           NoMethodError
       -------------
           kibana_install[kibana] (/tmp/kitchen/cache/cookbooks/mycookbook/providers/kibana.rb line 34) had an error: NoMethodError: undefined method `[]' for nil:NilClass
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/kibana_lwrp/libraries/install.rb:21:in `block in <class:KibanaInstall>'
           /tmp/kitchen/cache/cookbooks/kibana_lwrp/libraries/install.rb:116:in `kibana_resources'
           /tmp/kitchen/cache/cookbooks/kibana_lwrp/libraries/install.rb:46:in `block in <class:KibanaInstall>'
           
           Resource Declaration:
           ---------------------
       
           
            14: mycookbook_kibana "install_kibana" do
       
            16:     groupname 'kibana'
            17:     path_home '/opt'
            18: end
            19: 
           
       
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/mycookbook/recipes/kibana.rb:14:in `from_file'
           
           mycookbook_kibana("install_kibana") do
         action [:deploy]
         updated true
             updated_by_last_action true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :mycookbook_kibana
             cookbook_name "mycookbook"
             recipe_name "kibana"
             username "kibana"
             groupname "kibana"
             path_home "/opt"
           end
           
       
       Running handlers:
       [2016-02-23T02:21:05+00:00] ERROR: Running exception handlers
       Running handlers complete
       
       
       [2016-02-23T02:21:05+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-02-23T02:21:05+00:00] ERROR: mycookbook_kibana[install_kibana] (mycookbook::kibana line 14) had an error: NoMethodError: kibana_install[kibana] (/tmp/kitchen/cache/cookbooks/mycookbook/providers/kibana.rb line 34) had an error: NoMethodError: undefined method `[]' for nil:NilClass
       [2016-02-23T02:21:06+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
Am I supposed to call the kibana_lwrp cookbook differently ?

**Comment by martinb3** [comment] 2016-02-23 12:17
Hi there -- what version of this cookbook are you using? Your first stack trace looks like it is choking on `node['kibana']['git']['branch']`, which should be defined if your cookbook depends on this one -- since it's in https://github.com/lusis/chef-kibana/blob/master/attributes/default.rb#L9.

**Comment by ursvasan** [comment] 2016-02-23 17:23
Here is what i have in metadata.rb
```
depends          'kibana_lwrp', '~> 3.0.2'
```
I noticed that its getting null value for ```node['kibana']['git']['branch']``` and i added (copied from kibana_lwrp/attributes/default.rb) the following to my cookbook's default.rb 
# Values to use for git method of installation
default['kibana']['git']['url'] = 'https://github.com/elasticsearch/kibana'
default['kibana']['git']['branch'] = 'v3.1.2'
default['kibana']['git']['type'] = 'sync' # checkout | sync
default['kibana']['git']['config'] = 'kibana/config.js' # relative path of config file
default['kibana']['git']['config_template'] = 'config.js.erb' # template to use for config
default['kibana']['git']['config_template_cookbook'] = 'kibana_lwrp' # cookbook containing config template

**Comment by ursvasan** [comment] 2016-02-23 21:42
@martinb3 Do you have any suggestions to fix this issue ?

**Comment by martinb3** [comment] 2016-02-23 22:19
Attributes are loaded before libraries, so I'm not sure what to say. That attribute should be present. This cookbook isn't designed to be copied and pasted though -- it's designed to be used as a library. Unless you can point me at a Github repo or something else where I can reproduce the error, I'm unable to really help. The integration tests in this cookbook do run and converge without that error, as far as I know.

**Comment by ursvasan** [comment] 2016-02-24 02:15
@martinb3 Can you show me an example of how to call this cookbook as a library.

**Comment by ursvasan** [comment] 2016-02-24 07:35
@martinb3 you can look at my code [here](https://github.com/ursvasan/mycookbook). Just to be clear, I am not expecting everything to work with the code i posted, i created this cookbook to demonstrate how i am using the cookbook. when you run mycookbook you get the error i am talking about.

**Comment by martinb3** [comment] 2016-02-24 15:18
Thank you for supply an example -- I was able to isolate this to Chef 12.4.3. If I upgraded to 12.5.x, the problem went away. Alternately, I've [pushed a branch](https://github.com/lusis/chef-kibana/tree/chef_compat) you can try, which uses the chef_compat functionality to backport all of the current functionality to older versions of Chef.

**Comment by martinb3** [comment] 2016-02-24 15:19
If you have any feedback on that branch, I'd love to hear it. Might be something we can merge into master if it is working well.

**Comment by ursvasan** [comment] 2016-02-25 01:51
Yes, upgrading chef version to 12.5.x solved that problem. How do i point to the version in your feature branch from metadata.rb.

**Comment by martinb3** [comment] 2016-02-25 15:27
Hi there -- you'd have to use a Berksfile entry to do that.

```
cookbook 'kibana_lwrp', git: 'git://github.com/lusis/chef-kibana.git', branch: 'chef_compat'
```

**Comment by ursvasan** [comment] 2016-02-25 22:51
I did verify that your patch branch works. Thanks !

**Comment by martinb3** [comment] 2016-06-21 15:48
I've merged the chef_compat branch into master, and it should be available in the next release. Thanks for the report!

**Closed by martinb3** 2016-06-21 15:48 UTC
Labels: question
